In [3]:
import streamlit as st
import pandas as pd
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import numpy as np

In [4]:
data_import = pd.read_csv("melb_data.csv")
data_import.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [5]:
data_import.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [6]:
numerical_column_list = []
categorical_column_list = []

for i in data_import.columns:
    if data_import[i].dtype == np.int64 or data_import[i].dtype == np.float64:
        numerical_column_list.append(data_import[i])
    else:
        categorical_column_list.append(data_import[i])

In [7]:
numerical_data = pd.concat(numerical_column_list,axis=1)

In [8]:
categorical_data = pd.concat(categorical_column_list,axis=1)

In [9]:
numerical_data = numerical_data.apply(lambda x: x.fillna(np.mean(x)))

In [10]:
scaler = StandardScaler()

scaled_values = scaler.fit_transform(numerical_data)
scaled_values

array([[-9.81463370e-01,  6.32448029e-01, -1.30148498e+00, ...,
         1.21159582e-01,  3.06395829e-02, -7.84624806e-01],
       [-9.81463370e-01, -6.36397544e-02, -1.30148498e+00, ...,
         1.64368448e-02, -1.74781777e-02, -7.84624806e-01],
       [ 6.48761311e-02,  6.08984396e-01, -1.30148498e+00, ...,
        -1.22723149e-03, -7.85462560e-03, -7.84624806e-01],
       ...,
       [ 6.48761311e-02,  1.47532944e-01, -5.68760518e-01, ...,
        -5.49318283e-01, -1.03776717e+00, -2.45389260e-01],
       [ 1.11121563e+00,  2.22797508e+00, -5.68760518e-01, ...,
        -6.29311314e-01, -9.83779046e-01, -2.45389260e-01],
       [ 1.11121563e+00,  3.27420798e-01, -6.53961037e-01, ...,
        -3.37796006e-02, -1.06557924e+00, -2.08161223e-01]])

In [13]:
pca = PCA()
pca_data = pd.DataFrame(pca.fit_transform(scaled_values))
pca_data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,-1.564121,-0.325079,-1.130327,0.191528,-0.717489,0.219733,0.712520,0.174893,-0.615090,0.213752,-0.572346,0.225010,0.041184
1,-2.122226,-0.342978,-2.358250,0.314726,-0.969930,-0.442199,-0.746979,-0.640964,-0.264500,0.181520,0.526476,-0.146374,0.033447
2,-0.254488,-0.975053,-2.562902,0.256763,-0.843204,-0.333929,-0.317232,-1.273381,-0.054842,0.288952,0.896721,-0.212265,0.030998
3,-0.306214,-0.822116,-0.521124,-0.077741,-0.635277,0.312291,0.751094,-0.609893,-0.331681,0.078860,0.484233,-0.827125,-0.009448
4,0.340508,-0.859302,0.117898,-0.278671,-0.525022,0.685527,1.265098,0.350487,-0.587861,-0.564924,-1.795087,-0.461944,-0.748602
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,2.345971,1.492997,0.314294,-0.284973,-0.045758,0.231532,0.158201,-0.246655,-0.355963,-1.008716,0.162342,-0.067533,-0.004573
13576,0.028447,-1.042620,0.464903,-0.262049,-0.324336,0.650091,1.224244,0.513345,0.899776,-0.470574,0.191715,-0.087283,0.013811
13577,0.759100,-1.222932,0.879864,-0.315954,-0.126062,0.678185,1.121346,2.357686,0.554781,-0.210156,0.123896,-0.227848,0.017779
13578,2.289769,-1.928583,-1.388048,0.007186,-0.192441,-0.310384,-1.051976,3.433467,0.427617,-0.512475,-1.096820,0.224635,0.047016
13579,0.210348,-1.771378,-1.252011,-0.026519,-0.427230,-0.510509,-1.171438,-0.549808,0.711832,-0.961781,-0.465913,-0.351215,-0.002780

In [24]:
new_column_names = ["PCA_" + str(i) for i in range(1, len(pca_data.columns)+1)]

In [27]:
column_mapper = dict(zip(list(pca_data.columns),new_column_names))

In [32]:
pca_data = pca_data.rename(columns=column_mapper)
pca_data

,PCA_1,PCA_2,PCA_3,PCA_4,PCA_5,PCA_6,PCA_7,PCA_8,PCA_9,PCA_10,PCA_11,PCA_12,PCA_13
0,-1.564121,-0.325079,-1.130327,0.191528,-0.717489,0.219733,0.712520,0.174893,-0.615090,0.213752,-0.572346,0.225010,0.041184
1,-2.122226,-0.342978,-2.358250,0.314726,-0.969930,-0.442199,-0.746979,-0.640964,-0.264500,0.181520,0.526476,-0.146374,0.033447
2,-0.254488,-0.975053,-2.562902,0.256763,-0.843204,-0.333929,-0.317232,-1.273381,-0.054842,0.288952,0.896721,-0.212265,0.030998
3,-0.306214,-0.822116,-0.521124,-0.077741,-0.635277,0.312291,0.751094,-0.609893,-0.331681,0.078860,0.484233,-0.827125,-0.009448
4,0.340508,-0.859302,0.117898,-0.278671,-0.525022,0.685527,1.265098,0.350487,-0.587861,-0.564924,-1.795087,-0.461944,-0.748602
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,2.345971,1.492997,0.314294,-0.284973,-0.045758,0.231532,0.158201,-0.246655,-0.355963,-1.008716,0.162342,-0.067533,-0.004573
13576,0.028447,-1.042620,0.464903,-0.262049,-0.324336,0.650091,1.224244,0.513345,0.899776,-0.470574,0.191715,-0.087283,0.013811
13577,0.759100,-1.222932,0.879864,-0.315954,-0.126062,0.678185,1.121346,2.357686,0.554781,-0.210156,0.123896,-0.227848,0.017779
13578,2.289769,-1.928583,-1.388048,0.007186,-0.192441,-0.310384,-1.051976,3.433467,0.427617,-0.512475,-1.096820,0.224635,0.047016
13579,0.210348,-1.771378,-1.252011,-0.026519,-0.427230,-0.510509,-1.171438,-0.549808,0.711832,-0.961781,-0.465913,-0.351215,-0.002780

In [30]:
pca_data

,PCA_1,PCA_2,PCA_3,PCA_4,PCA_5,PCA_6,PCA_7,PCA_8,PCA_9,PCA_10,PCA_11,PCA_12,PCA_13
0,-1.564121,-0.325079,-1.130327,0.191528,-0.717489,0.219733,0.712520,0.174893,-0.615090,0.213752,-0.572346,0.225010,0.041184
1,-2.122226,-0.342978,-2.358250,0.314726,-0.969930,-0.442199,-0.746979,-0.640964,-0.264500,0.181520,0.526476,-0.146374,0.033447
2,-0.254488,-0.975053,-2.562902,0.256763,-0.843204,-0.333929,-0.317232,-1.273381,-0.054842,0.288952,0.896721,-0.212265,0.030998
3,-0.306214,-0.822116,-0.521124,-0.077741,-0.635277,0.312291,0.751094,-0.609893,-0.331681,0.078860,0.484233,-0.827125,-0.009448
4,0.340508,-0.859302,0.117898,-0.278671,-0.525022,0.685527,1.265098,0.350487,-0.587861,-0.564924,-1.795087,-0.461944,-0.748602
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,2.345971,1.492997,0.314294,-0.284973,-0.045758,0.231532,0.158201,-0.246655,-0.355963,-1.008716,0.162342,-0.067533,-0.004573
13576,0.028447,-1.042620,0.464903,-0.262049,-0.324336,0.650091,1.224244,0.513345,0.899776,-0.470574,0.191715,-0.087283,0.013811
13577,0.759100,-1.222932,0.879864,-0.315954,-0.126062,0.678185,1.121346,2.357686,0.554781,-0.210156,0.123896,-0.227848,0.017779
13578,2.289769,-1.928583,-1.388048,0.007186,-0.192441,-0.310384,-1.051976,3.433467,0.427617,-0.512475,-1.096820,0.224635,0.047016
13579,0.210348,-1.771378,-1.252011,-0.026519,-0.427230,-0.510509,-1.171438,-0.549808,0.711832,-0.961781,-0.465913,-0.351215,-0.002780

In [31]:
output = pd.concat([data_import,pca_data],axis=1)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,PCA_4,PCA_5,PCA_6,PCA_7,PCA_8,PCA_9,PCA_10,PCA_11,PCA_12,PCA_13
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,0.191528,-0.717489,0.219733,0.712520,0.174893,-0.615090,0.213752,-0.572346,0.225010,0.041184
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,0.314726,-0.969930,-0.442199,-0.746979,-0.640964,-0.264500,0.181520,0.526476,-0.146374,0.033447
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,0.256763,-0.843204,-0.333929,-0.317232,-1.273381,-0.054842,0.288952,0.896721,-0.212265,0.030998
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,-0.077741,-0.635277,0.312291,0.751094,-0.609893,-0.331681,0.078860,0.484233,-0.827125,-0.009448
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,-0.278671,-0.525022,0.685527,1.265098,0.350487,-0.587861,-0.564924,-1.795087,-0.461944,-0.748602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,-0.284973,-0.045758,0.231532,0.158201,-0.246655,-0.355963,-1.008716,0.162342,-0.067533,-0.004573
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,-0.262049,-0.324336,0.650091,1.224244,0.513345,0.899776,-0.470574,0.191715,-0.087283,0.013811
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,-0.315954,-0.126062,0.678185,1.121346,2.357686,0.554781,-0.210156,0.123896,-0.227848,0.017779
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,0.007186,-0.192441,-0.310384,-1.051976,3.433467,0.427617,-0.512475,-1.096820,0.224635,0.047016
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,-0.026519,-0.427230,-0.510509,-1.171438,-0.549808,0.711832,-0.961781,-0.465913,-0.351215,-0.002780